Repository TeamGrabit/Grabit_frontend, pull requests merged in 2022-07, with the labels that each got.

#39 챌린지 설정 페이지 API 연결
  src/components/SettingChallenge.svelte
  src/pages/MyChallengeList.svelte
  src/store/challenge.js
Labels: ✍ Api

#36 챌린지목록 페이징
  public/build/bundle.css
  public/build/bundle.js
  public/build/bundle.js.map
  src/common/fetch.js
  src/components/ChallengeBox.svelte
  src/components/PagingDiv.svelte
  src/components/Profile.svelte
  src/components/Toast.svelte
  src/pages/CreateChallenge.svelte
  src/pages/EditProfile.svelte
  src/pages/TotalChallengeList.svelte
  src/pages/index.js
  src/store/challenge.js
Labels: ✍ Api, ✨ Feature

#41 채팅 시스템 구현 ( API 연동, UI 수정 등 추가 작업 필요 )
  package-lock.json
  package.json
  public/build/bundle.css
  public/build/bundle.js
  public/build/bundle.js.map
  rollup.config.js
  src/App.svelte
  src/common/hook.js
  src/components/ChatButton.svelte
  src/components/ChatRoom.svelte
  src/store/challenge.js
  src/store/user.js
Labels: ✨ Feature

#43 userChallenge 스토어 분리 및 get userChallenge api 주소 변경
  package-lock.json
  public/build/bundle.css
  public/build/bundle.js
  public/build/bundle.js.map
  src/components/ChatButton.svelte
  src/pages/MyChallengeList.svelte
  src/store/challenge.js
  src/store/myChallenge.js
Labels: ✍ Api

#42 feat: EditProfile API 연결
  public/build/bundle.css
  public/build/bundle.js
  public/build/bundle.js.map
  src/common/fetch.js
  src/components/Header.svelte
  src/components/Profile.svelte
  src/pages/EditProfile.svelte
Labels: ✍ Api
